bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

liquidboards/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler400, handler403, handler404, handler405, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('blog/', include('blog.urls')),
    path('stores/', include('stores.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = 'liquidboards.views.handler400'
handler403 = 'liquidboards.views.handler403'
handler404 = 'liquidboards.views.handler404'
handler405 = 'liquidboards.views.handler405'
handler500 = 'liquidboards.views.handler500'

stores/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.StoreList.as_view(), name='stores'),
    path('<int:store_id>/', views.store_detail, name='store_detail'),
]

stores/models.py
from django.db import models


class Store(models.Model):
    """
    Model for a Store
    """
    name = models.CharField(max_length=200, unique=True)
    location = models.CharField(max_length=200, null=False, blank=False)
    about = models.TextField(max_length=500, null=False, blank=False)
    store_image_url = models.URLField(max_length=1024, null=True, blank=True)
    store_image = models.ImageField(null=True, blank=True)
    logo_url = models.URLField(max_length=1024, null=True, blank=True)
    logo_image = models.ImageField(null=True, blank=True)
    owner = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        """
        Magic Method, returns a string description of the object
        """
        return self.name


class StoreAddress(models.Model):
    """
    Model for a Store address
    """
    store = models.OneToOneField(
        Store, on_delete=models.CASCADE, primary_key=True)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    county = models.CharField(max_length=80, null=True, blank=True)
    country = models.CharField(max_length=80, null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        """
        Magic Method, returns a string description of the object
        """
        return f"{self.town_or_city} address"


class Staff(models.Model):
    """
    Model for a Staff members
    """
    first_name = models.CharField(max_length=200, null=False, blank=False)
    surname = models.CharField(max_length=200, null=False, blank=False)
    store = models.ForeignKey(
        Store, on_delete=models.CASCADE, related_name='staff'
        )
    staff_image_url = models.URLField(max_length=1024, null=True, blank=True)
    staff_image = models.ImageField(null=True, blank=True)
    job_title = models.CharField(max_length=200, null=False, blank=False)
    bio = models.TextField(blank=True)
    start_date = models.DateField(null=False, blank=False)
    staff_number = models.CharField(
        max_length=6, unique=True, null=False, blank=False
        )

    def __str__(self):
        """
        Magic Method, returns a string description of the object
        """
        return f" {self.first_name} {self.surname}"


class StaffAddress(models.Model):
    """
    Model for a Staff Contact details
    """
    staff = models.OneToOneField(
        Staff, on_delete=models.CASCADE, primary_key=True)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    county = models.CharField(max_length=80, null=True, blank=True)
    country = models.CharField(max_length=80, null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        """
        Magic Method, returns a string description of the object
        """
        return f"Staff address - {self.staff}"

stores/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Store, StoreAddress


class StoreList(generic.ListView):
    """
    display list of all stores
    """
    model = Store
    queryset = Store.objects.all().order_by('name')
    template_name = 'stores/stores.html'
    paginate_by = 3


def store_detail(request, store_id):
    """
    View to return individual store detail page
    """
    # queryset = Store.objects
    store = get_object_or_404(Store, pk=store_id)
    address = get_object_or_404(StoreAddress, pk=store)
    staff = store.staff.all()

    template = 'stores/store_detail.html'

    context = {
        'store': store,
        'address': address,
        'staff': staff,
    }

    return render(request, template, context)

stores/templates/stores/store_detail.html
{% extends "base.html" %}

{% load static %}

{% block extra_title %} - {{ store.location }} {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'stores/css/stores.css' %}">
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<!--  Store Details page -->
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>

<div class="overlay"></div>
<div class="container ">

    <!-- Display Store Details -->
    <div class="row">
        <div class="col  mb-4 mt-3">
            <div class="card-body mt-2">

                <!-- Display store logo image -->
                <div class="img_container bg-black mb-5" role="img"
                    aria-label="image of Liquid Boards Local Skateshop logo - sunset text on black background">

                    {% if store.logo_image %}
                    <img class="card-logo_store_details" src="{{ store.logo_image.url }}"
                        alt="liquid boards logo sunset-text on black background">
                    {% else %}
                    <img class="card-logo_store_details" src="{{ MEDIA_URL }}liquid-boards-logo.png"
                        alt="liquid boards logo sunset-text on black background">
                    {% endif %}
                </div>

                <div class="card-text text-grey text-center col-lg-6 offset-lg-3">
                    <p class="pt-5 mt-5"> {{ store.about }}</p>
                </div>

            </div>
        </div>
    </div>

    <h3 class=" reviews-header text-center text-muted"> Meet the Team</h3>

    <!-- for loop inside the empty control tags to iterate through each staff member in staff -->
    {% for staff in staff %}

    <div class="staff-card col-lg-10 offset-lg-1  col-xl-8 offset-lg-2 card mb-1  mt-3 ">

        <div class="card-body">
            <div class="row">
                <!-- Display staff image -->
                <div class="staff_img_detail w-100 h-100 mt-3" role="img"
                    aria-label="image for liquid boards local shop staff">

                    {% if staff.staff_image %}
                    <img class="card-staff_img_detail" src="{{ staff.staff_image.url }}" alt="image of staff">
                    {% else %}
                    <img class="card-staff_img_detail" src="{{ MEDIA_URL }}sunset-skater2.jpg"
                        alt="default image for staff">
                    {% endif %}

                </div>
            </div>
            <!-- The store address and details-->
            <div class=" text-muted mt-4 ">
                <p>
                    <strong class="text-black">
                        {{store.name  }}
                    </strong>
                </p>
                <p>
                    <strong class="text-muted">
                        {{ staff.job_title}}:
                    </strong>
                    <strong class="text-muted">
                        {{ staff.first_name}} {{ staff.surname}}
                    </strong>
                </p>
                <p class="pb-4">
                    <span class="text-muted">
                        {{ staff.bio }}
                    </span>
                </p>
                <hr class="text-grey w-75 mx-auto pb-4">
            </div>
        </div>
        <div class="text-center mt-5 mb-3">
            <a class="review-arrow-up " href="#top">
                <i class="fa fa-chevron-circle-up"></i>
            </a>
        </div>
    </div>
    <!-- for loop ends here -->
    {% endfor %}

    <!-- Display Store Details -->
    <div class="row">
        <div class="col  mb-4 mt-3">
            <div class="card-body mt-2">

                <!-- Display Store address -->
                <div class="card-text text-muted text-center ">

                    <p class="pt-4 font-weight-bold">Contact {{ store.name }}</p>

                    <p class="pt-3"> {{ address.street_address1 }}</p>
                    <p> {{ address.town_or_city }}</p>
                    <p> {{ address.county }}</p>
                    <p> {{ address.country }}</p>
                    <p> {{ address.postcode }}</p>

                    <p class="pt-4 nav-link font-weight-bold text-center"> {{ address.email }}</p>
                    <p class="pb-5 nav-link font-weight-bold"> {{ address.phone_number }}</p>

                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

stores/templates/stores/stores.html
{% extends "base.html" %}
{% load static %}
{% block extra_title %} - Local Shops {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'stores/css/stores.css' %}">
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}

<!-- Stores page -->
<section id="local-shops">
    <div class=" col-lg-8 mb-2 mt-3 mb-3 offset-lg-2 text-center">
        <h2 class="font-weight-bold">Local Skateshops</h2>
    </div>

    <div class="container-fluid">
        <div class="row">
            <!-- Display stores -->
            <div class="overlay"></div>
            <div class="col-xl-10 offset-xl-1  mt-3">
                <div class="row">

                    {% for store in store_list %}
                    <div class=" col-xl-4">

                        <div class="card-deck">
                            <div class="card mb-4">
                                <div class="card-body bg-black">
                                    <a href="{% url 'store_detail' store.id %}" class="blog-link">
                                        <div class="image-container" role="img"
                                            aria-label="image for liquid boards local shop">

                                            {% if store.logo_image %}
                                            <img class="card-img-top" src="{{ store.logo_image.url }}"
                                                alt="liquid boards logo sunset-text on black background">
                                            {% else %}
                                            <img class="card-img-top" src="{{ MEDIA_URL }}liquid-boards-logo.png"
                                                alt="liquid boards logo sunset-text on black background">
                                            {% endif %}

                                            {% if store.store_image %}
                                            <img class="card-img-bottom" src="{{ store.store_image.url }}"
                                                alt="liquid boards logo sunset-text on black background">
                                            {% else %}
                                            <img class="card-img-bottom" src="{{ MEDIA_URL }}noimage.png"
                                                alt="liquid boards logo sunset-text on black background">
                                            {% endif %}

                                            <div class="image-flash">
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>

                    </div>
                    {% if forloop.counter|divisibleby:3 %}
                </div>
                <div class="row">
                    {% endif %}
                    {% endfor %}
                </div>

                <!-- Pagination menu -->
                <div class="text-center mb-5">
                    {% if is_paginated %}
                    {% if page_obj.has_previous %}
                    <a class="btn btn-dark-outline  mb-4" href="?page=1">First</a>
                    <a class="btn btn-dark-outline  mb-4" href="?page={{ page_obj.previous_page_number }}">
                        <i class="fa fa-chevron-circle-left "></i>
                    </a>
                    {% endif %}

                    {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <a class=" btn btn-secondary mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                    <a class="btn btn-dark-outline mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <a class="btn btn-dark-outline mb-4" href="?page={{ page_obj.next_page_number }}">
                        <i class="fa fa-chevron-circle-right"></i></a>
                    <a class="btn btn-dark-outline mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                    {% endif %}
                    {% endif %}
                </div>

            </div>
        </div>

    </div>
</section>

{% endblock content%}