bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog'),
    path('<slug:slug>/', views.BlogDetail.as_view(), name='blog_detail'),
    path('like/<slug:slug>/', views.BlogLike.as_view(), name='blog_like'),
    path(
        'edit_comment/<int:comment_id>/',
        views.edit_comment, name='edit_comment'
        ),
    path(
        'delete_comment/<comment_id>/',
        views.delete_comment, name='delete_comment'
        ),
    ]

liquidboards/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler400, handler403, handler404, handler405, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('blog/', include('blog.urls')),
    path('stores/', include('stores.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = 'liquidboards.views.handler400'
handler403 = 'liquidboards.views.handler403'
handler404 = 'liquidboards.views.handler404'
handler405 = 'liquidboards.views.handler405'
handler500 = 'liquidboards.views.handler500'

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import UserProfile
from django.template.defaultfilters import slugify


class Blog(models.Model):
    """
    Model for Blog postings
    """
    title = models.CharField(
        max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog")
    created_on = models.DateTimeField(auto_now=True)
    updated_on = models.DateTimeField(auto_now=True)
    blog_image = models.ImageField('blog_image', default='placeholder')
    blog_image_url = models.URLField(max_length=1024, null=True, blank=True)
    content = models.TextField(blank=True, null=True)
    excerpt = models.TextField(max_length=100, blank=True)
    likes = models.ManyToManyField(
        User, related_name='like_blog', blank=True)

    class Meta:
        """
        Orders blog postings by date created - newest first
        """
        ordering = ['-created_on']

    def __str__(self):
        """
        Magic Method, returns a string description of the object
        """
        return self.title

    def number_of_likes(self):
        """
        Helper method, returns the amount of likes on a blog post
        """
        return self.likes.count()

    def save(self, *args, **kwargs):
        """
        slugify function from learndjango.com
        """
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Comment(models.Model):
    """
    Comments model. Authenticated members can comment on a blog
    """
    blog = models.ForeignKey(
        Blog, on_delete=models.CASCADE, related_name="comments")
    commenter = models.ForeignKey(
        UserProfile, related_name='comments',
        on_delete=models.CASCADE,
        default=""
        )
    name = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        """
        Orders blog posts by date created - oldest first
        """
        ordering = ['created_on']

    def __str__(self):
        """Magic Method, returns a string description of the object"""
        return f"Comment {self.body} by {self.name}"

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    """
    comments form
    """
    class Meta:
        model = Comment
        fields = ('body',)

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views import generic, View
from django.http import HttpResponseRedirect
from .models import Blog, Comment
from profiles.models import UserProfile
from .forms import CommentForm


class BlogList(generic.ListView):
    """
    display list of all blog posts
    """
    model = Blog
    queryset = Blog.objects.all().order_by('-created_on')
    template_name = 'blog/blog.html'
    paginate_by = 3


class BlogDetail(View):
    """
    display blog post details
    """

    def get(self, request, slug, *args, **kwargs):
        """
        get the blog post, check for comments and likes
        """
        queryset = Blog.objects
        blog = get_object_or_404(queryset, slug=slug)
        comments = blog.comments.order_by('created_on')
        liked = False
        if blog.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            'blog/blog_detail.html',
            {
                'blog': blog,
                'comments': comments,
                'liked': liked,
                'comment_form': CommentForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):
        """
        get the blog post, check for comments and likes
        """
        queryset = Blog.objects
        blog = get_object_or_404(queryset, slug=slug)
        comments = blog.comments.order_by('created_on')
        liked = False
        if blog.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.blog = blog
            user_profile = UserProfile.objects.get(user=request.user)
            comment.commenter = user_profile
            comment.save()
            messages.success(request, 'Your comment has been added ')

            return HttpResponseRedirect(reverse('blog_detail', args=[slug]))

        else:
            comment_form = CommentForm()

        return render(
            request,
            'blog/blog_detail.html',
            {
                'blog': blog,
                'comments': comments,
                'liked': liked,
                'comment_form': CommentForm()
            },
        )


class BlogLike(View):
    """
    Blog like feature
    """

    def post(self, request, slug, *args, **kwargs):
        """
        toggle likes on/off. two options.
        if user has liked a blog post then remove like.
        if user has not a blog post the add like.
        """
        blog = get_object_or_404(Blog, slug=slug)

        if blog.likes.filter(id=request.user.id).exists():
            blog.likes.remove(request.user)
            messages.success(
                request, 'You removed your Like from this blog post'
                )
        else:
            blog.likes.add(request.user)
            messages.success(request, 'You added a Like to this blog post')

        return HttpResponseRedirect(reverse('blog_detail', args=[slug]))


@login_required
def edit_comment(request, comment_id):
    """
    Edit a comment
    """

    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your comment has been \
            successfully updated.')
            return redirect(
                reverse('blog_detail', args=(comment.blog.slug,)))

        else:
            messages.error(request, 'Please try again.')
    else:
        form = CommentForm(instance=comment)

    template = 'blog/edit_comment.html'
    context = {
        'form': form,
        'comment': comment,
        'blog': comment.blog,
    }

    return render(request, template, context)


@login_required
def delete_comment(request, comment_id):
    """
    Delete a blog comment
    """
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user == comment.commenter.user or request.user.is_superuser:
        comment.delete()
        messages.success(request, 'Comment deleted!')
        return redirect(reverse('blog_detail', args=[comment.blog.slug]))
    else:
        messages.error(
            request,
            'Only shop owner and comment author can do that.')
        return redirect(reverse('blog_detail', args=[comment.blog.slug]))

blog/templates/blog/blog.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %} - Blog {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

{% block content %}

<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>

<!-- blog section -->
<div class="overlay"></div>
<section id="blog-posts">

    <div class="container-fluid">
        <div class="row">

            <!-- Display blogs -->
            <div class="col-xl-10 offset-xl-1 mt-4">
                <div class="row">
                    {% for blog in blog_list %}
                    <div class=" col-xl-4">
                        <a href="{% url 'blog_detail' blog.slug %}" class="blog-link">
                        <div class="card-deck">
                            <div class="card mb-4">
                                <div class="card-body blog-card">
                                    <!-- <a href="{% url 'blog_detail' blog.slug %}" class="blog-link"> -->
                                        <div class="image-container">
                                            {% if "placeholder" in blog.blog_image.url %}
                                            <img class="card-img-top" src="{{ MEDIA_URL }}noimage.png"
                                                alt="default image for blog">
                                            {% else %}
                                            <img class="card-img-top" src=" {{ blog.blog_image.url }}"
                                                alt="image of blog post">
                                            {% endif %}
                                            <div class="image-flash">

                                                <h4 class="post-title pt-2 ">{{ blog.title }}</h4>
                                    <!-- </a> -->
                                    <p class="card-text text-muted pb-1">by {{ blog.author }},
                                        {{ blog.created_on | date:"j F Y" }}</p>
                                    <hr class="text-grey w-75 mx-auto pb-3">
                                    <p class="text-muted "> {{ blog.excerpt }}</p>
                                </div>
                            </div>

                            <div>
                                <i class="fas fa-thumbs-up text-sunset"></i>
                                <span class="text-silver ">{{ blog.number_of_likes }}</span>
                            </div>
                        </div>

                    </div>
                </div>

            </a>
            
            </div>
            {% if forloop.counter|divisibleby:3 %}
        </div>
        <div class="row">
            {% endif %}
            {% endfor %}
        </div>

        <!-- Pagination menu -->
        <div class="text-center mb-5">
            {% if is_paginated %}
            {% if page_obj.has_previous %}
            <a class="btn btn-dark-outline  mb-4" href="?page=1">First</a>
            <a class="btn btn-dark-outline  mb-4" href="?page={{ page_obj.previous_page_number }}">
                <i class="fa fa-chevron-circle-left "></i>

            </a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
            <a class=" btn btn-secondary mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
            <a class="btn btn-dark-outline mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <a class="btn btn-dark-outline mb-4" href="?page={{ page_obj.next_page_number }}">
                <i class="fa fa-chevron-circle-right"></i></a>
            <a class="btn btn-dark-outline mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
            {% endif %}
        </div>
    </div>
    </div>
    </div>
</section>

{% endblock content%}

blog/templates/blog/blog_detail.html
{% extends "base.html" %}

{% load static %}

{% block extra_title %} - {{ blog.title }} {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<!-- Display Blog Details -->
<div class="overlay"></div>
<div class="container ">
    <div class="row">
        <div class="col-md-10 offset-md-1 col-xl-8 offset-xl-2 card mb-4 mt-3 left  top">
            <div class="card-body mt-2">

                <!-- Display blog image -->
                <div class="img_detail mt-3 mb-3">
                    {% if "placeholder" in blog.blog_image.url %}
                    <img class="card-img-top-post " src="{{ MEDIA_URL }}noimage.png" alt="default image for blog">
                    {% else %}
                    <img class="card-img-top-post" src=" {{ blog.blog_image.url }}" alt="image of blog">
                    {% endif %}
                </div>

                <h4 class="card-title text-black">{{ blog.title }}</h4>
                <p class="card-text text-muted">Blog post by {{ blog.author }}</p>
                <p class="card-text text-muted">Posted on {{ blog.created_on | date:"j F Y" }}</p>

                <div class="row ">
                    <div class=" ml-2 mb-3 ">
                        <!-- if user is authenticated display likes feature -->

                        {% if user.is_authenticated %}
                        <form class="d-inline" action="{% url 'blog_like' blog.slug %}" method="POST">
                            {% csrf_token %}
                            <strong>
                                {% if liked %}

                                <button type="submit" name="blog_id" value="{{blog.slug}}" class="btn-like"><i
                                        class="fas fa-thumbs-up text-sunset ml-3"></i></button>
                                {% else %}

                                <button type="submit" name="blog_id" value="{{blog.slug}}" class="btn-like"><i
                                        class="far fa-thumbs-up text-sunset ml-3"></i></button>
                                {% endif %}
                            </strong>
                        </form>
                        {% else %}
                        <span class="text-secondary"><i class="far fa-thumbs-up text-sunset ml-3"></i></span>
                        <span class="text-secondary">{{ blog.number_of_likes }}</span>
                        {% endif %}

                    </div>
                    <!-- chat icon with number of comments -->
                    <div class="col-3">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>

                <div class="card-text text-grey">
                    <hr class="text-grey w-75 mx-auto pb-4">
                    {{ blog.content | safe }}
                </div>

                <div class="row ">
                    <div class="mt-3 mb-3 ">

                        <!-- if user is authenticated display likes feature -->
                        {% if user.is_authenticated %}
                        <form class="d-inline" action="{% url 'blog_like' blog.slug %}" method="POST">
                            {% csrf_token %}
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <!-- <div class="row"> -->
        <div class="col-lg-10 offset-lg-1 col-xl-8 offset-xl-2 card mb-4  mt-3 ">
            <div class="card-body">

                <h3 class="text-center text-muted mt-3 mb-5"> Comments</h3>
                <!-- We want a for loop inside the empty control tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments text-muted mt-4 " style="padding: 25px;">

                    <!-- The body of the comment goes before the | -->

                    {{ comment.body | linebreaks }}

                    <p>
                        <span class=" text-muted ">
                            {{ comment.name }} {{ comment.created_on | date:" @ H:i j F Y " }}
                        </span>
                    </p>
                    <span class=" text-muted ">
                    </span>

                    {% if request.user.is_authenticated  %}
                    {% if request.user|lower == comment.name|lower or request.user.is_superuser %}

                    <small>
                        <a href="{% url 'edit_comment' comment.id %}">Edit</a> |
                        <a class="text-danger" href="{% url 'delete_comment' comment.id %}">Delete</a>
                    </small>
                    {% endif %}
                    {% endif %}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>

            {% if user.is_authenticated %}
            <div class="card-body ">

                <p class=" text-muted">Leave a comment . . </p>

                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-black rounded-0  mt-4">Submit</button>
                </form>

                <div class="text-center mt-5 mb-3">
                    <a class="arrow-up " href="#top">
                        <i class="fa fa-chevron-circle-up"></i>
                    </a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/edit_comment.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
<!--header-->
<div class="container header-container">
  <div class="row">
    <div class="col">
    </div>
  </div>
</div>
{% endblock %}
{% block content %}

<div class="container ">
  <div class="reviews-card col-md-8 offset-md-2 card mb-1">
    <div class="card-body ">

      <div class="row ">
        <div class="col-12 text-center ">
          <h2 class=" mb-4  text-black">Edit Blog Comment:
          </h2>
          <p> by {{ comment.name }}</p>
        </div>
      </div>
     
      <!-- form that allows the user to edit-->
      <div class="row pb-5">
        <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 p-5 ">
          <form method="POST" action="{% url 'edit_comment' comment.id %}" class="form mb-2"
            enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <!--buttons to update or cancel the process-->
            <div class="text-center">
              <button type="submit" class="btn btn-black rounded-0  mt-4">Submit</button>

              <a href="{% url 'blog_detail' blog.slug %}" class="btn btn-black rounded-0  mt-4">Cancel
              </a>
            </div>
          </form>
        </div>
      </div>

    </div>
  </div>
</div>
{% endblock %}